version: '3'
services:
  phpipam:
    ports:
      - "8050:80"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  dbnode:
    volumes:
      - "dbnode-mysql-data:/var/lib/mysql"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  dbnode-mysql-data:
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
