version: '3'
services:
  phpipam:
    restart: always
    ports:
      - "8050:80"
  dbnode:
    restart: always
    volumes:
      - "./mysql-data:/var/lib/mysql"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
